<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaymentMethodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();
        
        $paymentMethods = [
            [
                'id' => 1,
                'name' => 'Cash',
                'slug' => 'cash',
                'description' => 'Cash payment',
                'icon' => 'banknotes',
                'is_active' => true,
                'is_default' => true,
                'show_on_invoice' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'name' => 'Bank Transfer',
                'slug' => 'bank_transfer',
                'description' => 'Direct bank transfer / NEFT / RTGS / IMPS',
                'icon' => 'building-library',
                'is_active' => true,
                'is_default' => false,
                'show_on_invoice' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'name' => 'UPI',
                'slug' => 'upi',
                'description' => 'UPI payment (GPay, PhonePe, Paytm, etc.)',
                'icon' => 'device-phone-mobile',
                'is_active' => true,
                'is_default' => false,
                'show_on_invoice' => true,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'Credit Card',
                'slug' => 'credit_card',
                'description' => 'Credit card payment',
                'icon' => 'credit-card',
                'is_active' => true,
                'is_default' => false,
                'show_on_invoice' => true,
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'Debit Card',
                'slug' => 'debit_card',
                'description' => 'Debit card payment',
                'icon' => 'credit-card',
                'is_active' => true,
                'is_default' => false,
                'show_on_invoice' => true,
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'name' => 'Cheque',
                'slug' => 'cheque',
                'description' => 'Cheque / Demand Draft payment',
                'icon' => 'document-text',
                'is_active' => true,
                'is_default' => false,
                'show_on_invoice' => true,
                'sort_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'name' => 'PayPal',
                'slug' => 'paypal',
                'description' => 'PayPal online payment',
                'icon' => 'globe-alt',
                'is_active' => true,
                'is_default' => false,
                'show_on_invoice' => true,
                'sort_order' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'name' => 'Razorpay',
                'slug' => 'razorpay',
                'description' => 'Razorpay payment gateway',
                'icon' => 'bolt',
                'is_active' => true,
                'is_default' => false,
                'show_on_invoice' => true,
                'sort_order' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'name' => 'Stripe',
                'slug' => 'stripe',
                'description' => 'Stripe payment gateway',
                'icon' => 'bolt',
                'is_active' => true,
                'is_default' => false,
                'show_on_invoice' => true,
                'sort_order' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'name' => 'Net Banking',
                'slug' => 'net_banking',
                'description' => 'Internet banking payment',
                'icon' => 'computer-desktop',
                'is_active' => true,
                'is_default' => false,
                'show_on_invoice' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'name' => 'Wallet',
                'slug' => 'wallet',
                'description' => 'Digital wallet payment',
                'icon' => 'wallet',
                'is_active' => true,
                'is_default' => false,
                'show_on_invoice' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'name' => 'EMI',
                'slug' => 'emi',
                'description' => 'Equated Monthly Installment',
                'icon' => 'calendar',
                'is_active' => true,
                'is_default' => false,
                'show_on_invoice' => true,
                'sort_order' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'name' => 'Credit',
                'slug' => 'credit',
                'description' => 'Credit / On Account',
                'icon' => 'clock',
                'is_active' => true,
                'is_default' => false,
                'show_on_invoice' => false,
                'sort_order' => 13,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'name' => 'Other',
                'slug' => 'other',
                'description' => 'Other payment method',
                'icon' => 'ellipsis-horizontal',
                'is_active' => true,
                'is_default' => false,
                'show_on_invoice' => true,
                'sort_order' => 99,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('payment_methods')->insert($paymentMethods);
    }
}